name: multi_masked_formatter
description: Multple Masked TextInputFormatter Flutter plugin.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter